### ISSUE TITLE
Error on modeling after upgrade to 2.5.13

### ISSUE THREAD

**Issue by aseques** [zenoss/ZenPacks.zenoss.Microsoft.Windows#582]
I just upgraded the zenpack in my install to 2.5.13 from 2.5.10, and some errors appeared on one of the hosts when doing the modeling.

> Traceback (most recent call last): File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient datamaps = plugin.process(device, results, self.log) File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Microsoft.Windows-2.5.13.egg/ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py", line 106, in process if computerSystem.DomainRole in (BACKUPDC, PRIMARYDC): AttributeError: 'Item' object has no attribute 'DomainRole'

This host is a windows 2008r2 with no domain roles (only a member of the domain) with iis installed,

**Comment by aseques** [comment]
This is the full modeling log

```

2016-06-17 11:03:56,535 INFO zen.ZenModeler: Connecting to localhost:8789
2016-06-17 11:03:56,539 INFO zen.ZenModeler: Connected to ZenHub
2016-06-17 11:03:57,152 INFO zen.ZenModeler: Collecting for device wdocuware
2016-06-17 11:03:59,234 INFO zen.ZenModeler: No WMI plugins found for wdocuware
2016-06-17 11:03:59,235 INFO zen.ZenModeler: Python collection device wdocuware
2016-06-17 11:03:59,236 INFO zen.ZenModeler: plugins: zenoss.winrm.OperatingSystem, zenoss.winrm.CPUs, zenoss.winrm.FileSystems, zenoss.winrm.Interfaces, zenoss.winrm.Services, zenoss.winrm.Processes, zenoss.winrm.Software
2016-06-17 11:03:59,523 INFO zen.ZenModeler: No command plugins found for wdocuware
2016-06-17 11:03:59,523 INFO zen.ZenModeler: SNMP monitoring off for wdocuware
2016-06-17 11:03:59,523 INFO zen.ZenModeler: No portscan plugins found for wdocuware
2016-06-17 11:04:08,099 INFO zen.PythonClient: Python client finished collection for wdocuware
2016-06-17 11:04:08,099 INFO zen.ZenModeler: Modeler zenoss.winrm.FileSystems processing data for device wdocuware
2016-06-17 11:04:08,099 INFO zen.ZenModeler: Ignoring A: on wdocuware because it matches zFileSystemMapIgnoreTypes
2016-06-17 11:04:08,100 INFO zen.ZenModeler: Ignoring D: on wdocuware because it matches zFileSystemMapIgnoreTypes
2016-06-17 11:04:08,101 INFO zen.ZenModeler: Modeler zenoss.winrm.CPUs processing data for device wdocuware
2016-06-17 11:04:08,102 INFO zen.ZenModeler: Modeler zenoss.winrm.Services processing data for device wdocuware
2016-06-17 11:04:08,111 INFO zen.ZenModeler: Modeler zenoss.winrm.Software processing data for device wdocuware
2016-06-17 11:04:08,131 INFO zen.ZenModeler: Modeler zenoss.winrm.OperatingSystem processing data for device wdocuware
2016-06-17 11:04:08,131 WARNING zen.ZenModeler: No results returned for Win32_ComputerSystem. Check WMI namespace and DCOM permissions.
2016-06-17 11:04:08,132 ERROR zen.ZenModeler: Problem while executing plugin zenoss.winrm.OperatingSystem
2016-06-17 11:04:08,133 ERROR zen.ZenModeler: Traceback (most recent call last):
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient
datamaps = plugin.process(device, results, self.log)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Microsoft.Windows-2.5.13.egg/ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py", line 106, in process
if computerSystem.DomainRole in (BACKUPDC, PRIMARYDC):
AttributeError: 'Item' object has no attribute 'DomainRole'
2016-06-17 11:04:08,134 INFO zen.ZenModeler: Modeler zenoss.winrm.Processes processing data for device wdocuware
2016-06-17 11:04:09,605 INFO zen.ZenModeler: Modeler zenoss.winrm.Interfaces processing data for device wdocuware
2016-06-17 11:04:10,398 INFO zen.ZenModeler: No change in configuration detected
2016-06-17 11:04:10,399 INFO zen.ZenModeler: Scan time: 13.25 seconds
2016-06-17 11:04:10,410 INFO zen.ZenModeler: Daemon ZenModeler shutting down

```

**Comment by aseques** [comment]
Doing the same query on the server with the same user I get the proper results

>> PS C:\Windows\system32> foreach ($ObjItem in $CompConfig) {
>> $Role = $ObjItem.DomainRole
>> Switch ($Role) {
>> 0 {"Standalone Workstation"}
>> 1 {"Member Workstation"}
>> 2 {"Standalone Server"}
>> 3 {"Member Server"}
>> 4 {"Backup Domain Controller"}
>> 5 {"Primary Domain Controller"}
>> default {"Not a known Domain Role"}
>>          }
>> }
>>
Member Server

**Comment by aseques** [comment]
It has been fixed on the upcomming 2.7.0 See the bug here https://jira.zenoss.com/browse/ZPS-563
